### ISSUE TITLE
Using as a library

### ISSUE THREAD

**Issue by stevenroose** [hipstermojo/paperoni#8]
Hey! I'm interested in a Rust library that can perform the "mozilla readability" algorithm. I noticed that paperoni is not using any third party dependency to do the algorithm, does that mean that you implemented it yourself?

Is it possible to use paperoni as a library?

I noticed there is a Rust version of the readability library: https://github.com/kumabook/readability 
Have you considered using that and contributing to it?

Cheers, great work!

**Comment by hipstermojo** [comment]
Hi @stevenroose . Yes I wrote the algorithm myself based on the Mozilla implementation though the version I ported is probably like 6 months old by now in terms of commit history. I wrote a blog on the same if you're interested.

Currently Paperoni is only packaged as a binary though I did have plans to get my readability version as a library for 3rd party use. Unfortunately it's not complete because I haven't updated that code in a while (not that a lot has changed) and I can't call it "fully compliant" yet since I haven't got the full test suite from the original repo run against my implementation.

Concerning the other readability crate (and its fork). I did look at them initially but after some rudimentary tests I found it to be insufficient for my needs. It is worth noting that it follows the Arc90 implementation which is slightly different from what Mozilla has.

**Comment by hipstermojo** [comment]
It's been about a week now since responding to this issue so I assume that my answer was sufficient, therefore, I'll be closing this. Nevertheless, when I update the readability port and get it out as an independent crate, I'll be sure to link this issue so you know.
